# docker-compose up -d
# docker-compose down
# docker exec -it freepbx bash

version: '2'
services:
  freepbx:
#    build: .
    image: mima84/docker-freepbx
    container_name: freepbx

    network_mode: "host"
#    ports:
#    - "5160-5161:5160-5161/udp"
#    - "5060-5060:5060-5060/udp"
#    - "8082:80/tcp"
#    - "10000-10050:10000-10050/udp"

    volumes:
    - ~/.freepbx/backup:/var/spool/asterisk/backup
    - /etc/hostname:/etc/hostname:ro
